### ISSUE TITLE
Order of team names and odds switched

### ISSUE THREAD

**Issue by bzarek** [bzarek/football-vis#6]
@DiabolicalDataDavid in week 3, the spread comes before the team name, which is reversed from previous weeks

**Comment by DiabolicalDataDavid** [comment]
@bzarek whoops, I’ll fix it tomorrow. It’s super easy, just forgot what way I did it beforehand

**Comment by bzarek** [comment]
No worries. I manually changed week 3 in the spreadsheet, but it would be nice to fix it for week 4

**Comment by bzarek** [comment]
verified in week 4 Thursday game form
